In [1]:
from IPython.display import display
import pandas as pd

import main_analysis as ma

RESULTS_DIR = 'results'
SUBJECTSUBJECT_CORRELATIONS_CSV_PATH = f'{RESULTS_DIR}/subjectsubject_correlations_nsd515.csv'
MODELSUBJECT_CORRELATIONS_CSV_PATH = f'{RESULTS_DIR}/modelsubject_correlations_nsd515.csv'

pixdim[1,2,3] should be non-zero; setting 0 dims to 1

In [2]:
core_frois = ['FFA', 'PPA', 'EBA']
all_frois = ['FFA', 'OFA', 'PPA', 'OPA', 'EBA', 'RSC', 'FBA', 'VWFA', 'OVWFA']
frois = core_frois
tthreshold = 7

to_model_names = ma.get_model_names('task_optimized')
model_localizer = 'grillspector'
best_model = 'vitb16siglip2res224'
metrics = ['pearsonr', 'rdmr'] # 'normed_pearsonr' 'pearsonr'

## Subject-Subject correlation

In [3]:
for metric in metrics:
    print(f'\n=== SUBJECT-SUBJECT correlations: {metric} ===')
    sbjsbj_csv = pd.read_csv(SUBJECTSUBJECT_CORRELATIONS_CSV_PATH)
    sbjsbj_csv = sbjsbj_csv[
        (sbjsbj_csv['fmri_froi'].isin(frois)) &
        (sbjsbj_csv['fmri_tthreshold'] == tthreshold)
    ]
    sbjsbj_csvgrouped = sbjsbj_csv.groupby('fmri_froi')[metric].median().reset_index()
    display(sbjsbj_csvgrouped)
    print(sbjsbj_csvgrouped[metric].median())

=== SUBJECT-SUBJECT correlations: pearsonr ===

  fmri_froi  pearsonr
0       EBA  0.712066
1       FFA  0.745145
2       PPA  0.696396

0.71206552

=== SUBJECT-SUBJECT correlations: rdmr ===

  fmri_froi      rdmr
0       EBA  0.471961
1       FFA  0.484948
2       PPA  0.377385

0.47196127548172784

# Model-Subject correlation

In [5]:
for metric in metrics:
    print(f'\n=== MODEL-SUBJECT correlations: {metric} ===')
    mdlsbj_csv = pd.read_csv(MODELSUBJECT_CORRELATIONS_CSV_PATH)
    mdlsbj_csv = mdlsbj_csv[
        (mdlsbj_csv['model_name'].isin(to_model_names)) &
        (mdlsbj_csv['fmri_froi'].isin(frois)) &
        (mdlsbj_csv['fmri_tthreshold'] == tthreshold) &
        (mdlsbj_csv['model_froi'].isin(frois)) &
        (mdlsbj_csv['model_tthreshold'] == tthreshold) &
        (mdlsbj_csv['model_localizer'] == model_localizer) &
        (mdlsbj_csv['model_name'].isin(to_model_names))
    ]
    # print(mdlsbj_csv[metric].median())
    mdlsbj_csvgrouped = mdlsbj_csv.groupby(['model_name', 'fmri_froi'])[metric].median().reset_index()
    mdlsbj_csvgrouped2 = mdlsbj_csvgrouped.groupby('fmri_froi')[metric].median().reset_index()
    print(mdlsbj_csvgrouped2[metric].median())


# best_mdlsbj_csv = mdlsbj_csv[
#     (mdlsbj_csv['model_name'].isin(to_model_names)) &
#     (mdlsbj_csv['fmri_froi'].isin(frois)) &
#     (mdlsbj_csv['fmri_tthreshold'] == tthreshold) &
#     (mdlsbj_csv['model_froi'].isin(frois)) &
#     (mdlsbj_csv['model_tthreshold'] == tthreshold) &
#     (mdlsbj_csv['model_localizer'] == model_localizer) &
#     (mdlsbj_csv['model_name'] == best_model)
# ]
# best_mdlsbj_csvgrouped = best_mdlsbj_csv.groupby(['model_name', 'fmri_froi'])[metric].median().reset_index()
# best_mdlsbj_csvgrouped2 = best_mdlsbj_csvgrouped.groupby('fmri_froi')[metric].median().reset_index()
# print(best_mdlsbj_csvgrouped2[metric].median())

=== MODEL-SUBJECT correlations: pearsonr ===
0.56809508

=== MODEL-SUBJECT correlations: rdmr ===
0.21725365127517543

In [7]:
mdlsbj_csvgrouped

              model_name fmri_froi      rdmr
0     alexnetbarlowtwins       EBA  0.185147
1     alexnetbarlowtwins       FFA  0.207991
2     alexnetbarlowtwins       PPA  0.232795
3    alexnetimagenet1kv1       EBA  0.183527
4    alexnetimagenet1kv1       FFA  0.316267
..                   ...       ...       ...
100        vitl14kosmos2       FFA  0.155987
101        vitl14kosmos2       PPA  0.227038
102     vitl14openaiclip       EBA  0.177678
103     vitl14openaiclip       FFA  0.387570
104     vitl14openaiclip       PPA  0.149017

[105 rows x 3 columns]

In [65]:
mdlsbj_csv

,model_name,model_layer,model_froi,model_tthreshold,model_localizer,fmri_dataset,fmri_froi,fmri_tthreshold,subject,normed_pearsonr,pearsonr,normed_rdmr,rdmr,pvalue_rdmr,pvalue_pearsonr,fmri_splithalf_pearsonr,fmri_splithalf_rdmr
0,alexnetimagenet1kv1,features.11,FFA,7,grillspector,nsd515,FFA,7,1,0.579079,0.524384,0.356567,0.264244,0.0,1.011229e-37,0.820017,0.549200
2,alexnetimagenet1kv1,features.12,EBA,7,grillspector,nsd515,EBA,7,1,0.509453,0.457236,0.259660,0.194928,0.0,5.709499e-28,0.805513,0.563560
4,alexnetimagenet1kv1,features.12,PPA,7,grillspector,nsd515,PPA,7,1,0.619488,0.538884,0.198041,0.131808,0.0,3.969849e-40,0.756702,0.442968
7,alexnetimagenet1kv1,features.11,FFA,7,grillspector,nsd515,FFA,7,2,0.657376,0.597486,0.502901,0.380867,0.0,3.774516e-51,0.826090,0.573563
9,alexnetimagenet1kv1,features.12,EBA,7,grillspector,nsd515,EBA,7,2,0.496988,0.431335,0.269299,0.192396,0.0,9.474955e-25,0.753248,0.510411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1948,convnexttinyimagenet1kv1,features.5.7.block.3,EBA,7,grillspector,nsd515,EBA,7,7,0.724770,0.612722,0.519005,0.346175,0.0,2.113391e-54,0.714703,0.444887
1950,convnexttinyimagenet1kv1,features.5.2.block.3,PPA,7,grillspector,nsd515,PPA,7,7,0.806977,0.595580,0.595779,0.281019,0.0,9.363155e-51,0.544700,0.222485
1953,convnexttinyimagenet1kv1,features.5.7.block.3,FFA,7,grillspector,nsd515,FFA,7,8,0.627813,0.505135,0.472118,0.276250,0.0,1.058845e-34,0.647372,0.342375
1955,convnexttinyimagenet1kv1,features.5.7.block.3,EBA,7,grillspector,nsd515,EBA,7,8,0.724700,0.516433,0.671391,0.305870,0.0,1.886664e-36,0.507821,0.207550
1957,convnexttinyimagenet1kv1,features.5.2.block.3,PPA,7,grillspector,nsd515,PPA,7,8,0.868273,0.667418,0.772540,0.337384,0.0,1.103390e-67,0.590858,0.190725

In [60]:
display(mdlsbj_csvgrouped2)
display(best_mdlsbj_csvgrouped2)

  fmri_froi  pearsonr
0       EBA  0.568095
1       FFA  0.526903
2       PPA  0.596953

  fmri_froi  pearsonr
0       EBA  0.637470
1       FFA  0.550327
2       PPA  0.586960

In [63]:
mdlsbj_csvgrouped3 = mdlsbj_csvgrouped.groupby('fmri_froi')['pearsonr'].max().reset_index()
mdlsbj_csvgrouped3

  fmri_froi  pearsonr
0       EBA  0.637470
1       FFA  0.668195
2       PPA  0.676550